Bb 17 navbar component
plextech-curriculum-sp23/bear-buddies pull request #10
Opened 2023-04-06 00:03 UTC by brunobmv

## Describe your changes:
Created navbar component that can be used in every page (just need to add it to the JSX)

## Proof that your changes work (include screenshots and/or for frontend):
<img width="1440" alt="Screen Shot 2023-04-05 at 17 01 15" src="https://user-images.githubusercontent.com/102827885/230239635-1ae82b68-038d-43d7-b31f-b9ed69275957.png">

## Jira Issue ticket number and link:
https://bearbuddies.atlassian.net/browse/BB-17?atlOrigin=eyJpIjoiZDNjNDgxM2NhZTdmNGY3NmE3YTcwZmQzNjJhNDkyMWEiLCJwIjoiaiJ9
BB-17

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have DM'd the group chat that I have made a PR and need reviewers.
- [x] I haved moved the Jira issue to "Under Review"
- [x] I have run `npx eslint filename.js` on all JavaScript files I've changed in this PR and fixed all displayed errors
- [x] I have checked the Chrome console in Developer Tools to make sure there are no significant errors

2023-04-06 00:47 UTC, DylanHopkins21 requested changes
Is there any chance you could make the text blue onHover? just would feel much better

2023-04-06 00:47 UTC, DylanHopkins21 commented on src/components/NavBar/NavBar.module.css
idk if we have specific styling for the css files (if it should be alphabetical or smth) if not then this is chill

2023-04-06 00:47 UTC, DylanHopkins21 commented on src/pages/SignupPage/SignupPage.js
trusting this is all good, no idea what you actually changed here. Next time don't include unrelated files in your PR

2023-04-06 23:25 UTC, thomaspwang approved these changes
looks good to me! just change what dylan requested (blue hover)

2023-04-06 23:25 UTC, thomaspwang commented on src/pages/SignupPage/SignupPage.js
@brunobmv what did you need to change in signup? generally you want to describe any changes in the PR

2023-04-07 07:56 UTC, brunobmv commented
Fixed all suggestions. no more changes to signup which i just used to visualize my changes to the component, and the hover works well. I think it is ready to merge to main

2023-04-07 20:29 UTC, DylanHopkins21 approved these changes
Looks fire, good job!

2023-04-08 17:27 UTC, merged