Bb 44 create api routes
plextech-curriculum-sp23/bear-buddies pull request #15
Opened 2023-04-18 07:55 UTC by DylanHopkins21

## Describe your changes:
Created routes for all described in Jira ticket

## Proof that your changes work:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/112282141/232708865-692717ae-dfc6-449d-a9fd-bf39bc2cfee9.png">
<img width="886" alt="image" src="https://user-images.githubusercontent.com/112282141/232708960-3b75ae9d-7b54-462c-8341-0a7f0b86f743.png">
<img width="845" alt="image" src="https://user-images.githubusercontent.com/112282141/232709321-4f3f6eee-02aa-4bdf-a20b-4f4782ddeb90.png">
<img width="858" alt="image" src="https://user-images.githubusercontent.com/112282141/232709532-b3950ecb-aaf4-4666-bbe5-464ca674124a.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/112282141/232709673-b205a207-3ac9-4054-981d-ff9ec6f50949.png">
<img width="852" alt="image" src="https://user-images.githubusercontent.com/112282141/232709854-a3f041df-5b46-4413-9ada-fadf875e78c2.png">
<img width="852" alt="image" src="https://user-images.githubusercontent.com/112282141/232710025-e287add8-b934-4f43-a3a2-f0474a59dd36.png">

## Jira Issue ticket number and link:
BB-44
https://bearbuddies.atlassian.net/jira/software/projects/BB/boards/1?selectedIssue=BB-44

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have DM'd the group chat that I have made a PR and need reviewers.
- [ ] I haved moved the Jira issue to "Under Review"
- [ ] I have run `npx eslint filename.js` on all JavaScript files I've changed in this PR and fixed all displayed errors
- [ ] I have checked the Chrome console in Developer Tools to make sure there are no significant errors
- [ ] If I have created any API routes, I have verified that they work on Postman.

2023-04-18 18:33 UTC, brunobmv requested changes, later dismissed
so for updating the user, can you only change the graduation year or anything you want? you probably dont want people to change their first and last names...
so maybe i would change what you can and cannot modify
maybe you should be able to modify the:
email, password, gender (i guess... this is berkeley), phone number, and grad year
and the first and last you shouldn't

2023-04-18 20:07 UTC, DylanHopkins21 commented
> so for updating the user, can you only change the graduation year or anything you want? you probably dont want people to change their first and last names... so maybe i would change what you can and cannot modify maybe you should be able to modify the: email, password, gender (i guess... this is berkeley), phone number, and grad year and the first and last you shouldn't

2023-04-18 21:14 UTC, thomaspwang approved these changes
LGTM

2023-04-19 22:50 UTC, brunobmv approved these changes

2023-04-19 22:56 UTC, merged