Bb 32 implement login sign up logic
plextech-curriculum-sp23/bear-buddies pull request #17
Opened 2023-04-25 02:29 UTC by brunobmv

## Describe your changes:
created signup page that:
- gets inputs from the users
- checks if the passwords match
- checks if the password has at least 8 characters
- checks if the email is already registered
- checks if all the fields are filled in
- then redirects the user to the login page and adds the user to the database.

## Proof that your changes work:
- For frontend changes, include screenshots / videos of the UI
- For backend changes, include screenshots of successful Postman API calls

https://user-images.githubusercontent.com/102827885/234159775-a7c74e73-4f06-4d92-aeae-3f82408994eb.mov

## Jira Issue ticket number and link:

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have DM'd the group chat that I have made a PR and need reviewers.
- [x] I haved moved the Jira issue to "Under Review"
- [x] I have run `npx eslint filename.js` on all JavaScript files I've changed in this PR and fixed all displayed errors
- [x] I have checked the Chrome console in Developer Tools to make sure there are no significant errors
- [x] If I have created any API routes, I have verified that they work on Postman.

2023-04-25 23:00 UTC, thomaspwang requested changes
Nice work! Needs some changes though

2023-04-25 23:00 UTC, thomaspwang commented on frontend/src/pages/SignupPage/SignupPage.js
Make sure to clean up all the code! Remove unnecessary comments, code, etc.

2023-04-25 23:00 UTC, thomaspwang commented on frontend/src/pages/SignupPage/SignupPage.js
> +    const [user, setUser] = useAtom(currUser);
Make sure to implement the logic where upon a successful sign-up or log-in, the user atom is set properly.

2023-04-25 23:00 UTC, thomaspwang commented on frontend/src/pages/SignupPage/SignupPage.js
When a user signs up, direct them to the home page, not login page.

2023-04-25 23:00 UTC, thomaspwang commented on frontend/src/pages/LoginPage/LoginPage.js
make sure to implement login logic! 

![image](https://user-images.githubusercontent.com/82493352/234424342-5f8d5ee9-2630-48e9-9d48-bcee43582b70.png)

2023-04-25 23:00 UTC, thomaspwang commented on frontend/src/pages/LoginPage/LoginPage.js
Note that for 1.c, this means you must do conditional routing in index.js:

1. If a user is logged-in (aka the currUser atom is not null), direct them to the home page

2. Otherwise, direct them to the login page

2023-04-26 17:14 UTC, DylanHopkins21 commented on frontend/src/pages/SignupPage/SignupPage.js
wait but almost every website redirects to loginpage after sign up i feel?

2023-04-26 23:06 UTC, brunobmv commented on frontend/src/pages/SignupPage/SignupPage.js
i kinda agree with DHop

2023-04-27 06:56 UTC, DylanHopkins21 requested changes
Hey Bruno, requested one quick change about the app.py but if I am mistaken about the merge error then you can resolve it and I can approve. My other comments can just be changed through github, either i can do it or you. Otherwise good job and thanks for rushing this through for me!

2023-04-27 06:56 UTC, DylanHopkins21 commented on backend/app.py
Wait make sure you pull from main cause we merged my branch that did a bunch of work towards app.py routing. I know you don't use any of my routes but I think it's necessary to avoid merge conflicts

2023-04-27 06:56 UTC, DylanHopkins21 commented on frontend/src/pages/SignupPage/SignupPage.js
> +            || graduationYear == '' || major == '';
lmao very funny way to do it but if it works it works

2023-04-27 06:56 UTC, DylanHopkins21 commented on frontend/src/pages/SignupPage/SignupPage.js
> +            console.log("not null");
let's try and remove all our console.log if it doesn't serve like a functional purpose

2023-04-27 06:56 UTC, DylanHopkins21 commented on frontend/src/pages/SignupPage/SignupPage.js
> +            console.log(user);
see previous

2023-04-27 18:09 UTC, brunobmv commented on backend/app.py
ok will do

2023-04-28 18:35 UTC, DylanHopkins21 approved these changes
LGTM

2023-04-28 19:38 UTC, thomaspwang approved these changes
LGTM POGGERSSS

2023-04-28 19:41 UTC, merged