Bb 22 log in page
plextech-curriculum-sp23/bear-buddies pull request #2
Opened 2023-03-22 08:29 UTC by brunobmv

## Describe your changes:
Created login page and used Bootstrap forms to create boxes and interactive buttons for the page.
Added a js file for the page and a css file for this page's styling.

## Proof that your changes work (include screenshots if frontend):

<img width="1439" alt="Screen Shot 2023-03-22 at 01 24 51" src="https://user-images.githubusercontent.com/102827885/226842936-05ed1d53-fa89-4c89-993c-24f69b9ab485.png">

## Jira Issue ticket number and link:

https://bearbuddies.atlassian.net/browse/BB-22?atlOrigin=eyJpIjoiZDgwYmM2NmQ0YmJiNGUyNTg2NGVlMWU1YzBlNGY4MjUiLCJwIjoiaiJ9

BB-22

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have DM'd the group chat that I have made a PR and need reviewers.
- [x] I haved moved the Jira issue to "Under Review"

2023-03-22 09:33 UTC, thomaspwang commented
This looks great! Love it. Just two small comments:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/82493352/226860287-10b6c3ea-9354-4f60-a5ad-e8ac77afa048.png">

Reduce this space by just a little bit, I think there's too much space between the title and the first bar

<img width="325" alt="image" src="https://user-images.githubusercontent.com/82493352/226860712-d1f46498-8fb3-43b9-81f6-c762afe9c523.png">

Make sure the "not a member"  text and the "join the community" button are aligned! also make them slightly closer to one another

2023-03-22 09:46 UTC, thomaspwang requested changes
Good work! Looks amazing. Just some minor changes needed before we should merge to main :))

2023-03-22 09:46 UTC, thomaspwang commented on src/pages/Login/login.js
This looks great! Love it. Just two small comments:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/82493352/226860287-10b6c3ea-9354-4f60-a5ad-e8ac77afa048.png">

Reduce this space by just a little bit, I think there's too much space between the title and the first bar

<img width="325" alt="image" src="https://user-images.githubusercontent.com/82493352/226860712-d1f46498-8fb3-43b9-81f6-c762afe9c523.png">

Make sure the "not a member"  text and the "join the community" button are aligned! also make them slightly closer to one another

2023-03-22 09:46 UTC, thomaspwang commented on src/pages/Login/login.js
> +*/
Remove unnecessary comments!

2023-03-22 09:46 UTC, thomaspwang commented on src/pages/_app.js
app.js shouldn't be changed

2023-03-22 09:46 UTC, thomaspwang commented on src/pages/Login/login.js
> +import {Button} from "react-bootstrap";
Be consistent with import syntax: so

import Button from "react-bootstrap/Button"

2023-03-22 09:46 UTC, thomaspwang commented on src/pages/Login/login.js
> +            <div className="not-member">
since this is a container should probably name it container as "not-member" is not the most descriptive, so maybe "bottom-container" or "not-member-container", or whatever you think is best

2023-03-22 09:46 UTC, thomaspwang commented on src/pages/Login/login.js
<img width="288" alt="image" src="https://user-images.githubusercontent.com/82493352/226862939-c5f272ea-6f47-4e8c-9e69-0e86fd4fab1e.png">

Make sure the buttons are the exact same styling, and also make them a bit rounder

2023-03-22 09:46 UTC, thomaspwang commented on src/pages/Login/login.js
> +
remove unnecessary empty lines

2023-03-22 09:46 UTC, thomaspwang commented on src/pages/Login/login.js
> +                    <Form.Group className="mb-3" controlId="formBasicPassword">
remove unnecessary empty lines

2023-03-22 09:46 UTC, thomaspwang commented on src/pages/Login/login.js
for text, I think we decided to use DM Sans, so use DM Sans for all the text.

2023-03-22 09:46 UTC, thomaspwang commented on src/pages/Login/login.js
<img width="500" alt="image" src="https://user-images.githubusercontent.com/82493352/226863976-5bd27165-c353-4383-9517-e4cadce263db.png">

make sure the title is bolded

2023-03-22 23:02 UTC, thomaspwang requested changes

2023-03-22 23:02 UTC, thomaspwang commented on src/pages/Login/login.css
> +    height: 50px;
rename tjos attrobite

2023-03-23 01:20 UTC, brunobmv commented
![Screen Shot 2023-03-22 at 18 20 09](https://user-images.githubusercontent.com/102827885/227074277-9348f335-d4a0-4749-a114-165469adfe23.jpg)

2023-03-23 01:38 UTC, thomaspwang requested changes
Almost there! Just a few small things

2023-03-23 01:38 UTC, thomaspwang commented on src/pages/Login/login.js
components and pages should be capitalized so

- Login.js
- Login.module.css

2023-03-23 01:38 UTC, thomaspwang commented on src/pages/Login/login.js
<img width="212" alt="image" src="https://user-images.githubusercontent.com/82493352/227075327-6f94c226-be9a-4eb1-907d-7b1cf31a2de7.png">

couple super small UI details
- "not a member" text should be the same styling as "join the community" 
- the "not a member" and "join the community" should be centered (they skew left)
- the "join the community" is a little lower than "not a member"

2023-03-23 01:38 UTC, thomaspwang commented on src/pages/Login/login.js
[scrnli_3_22_2023_6-37-33 PM.webm](https://user-images.githubusercontent.com/82493352/227076671-a22585a2-b3e8-443d-9f76-7f3c96dc7e13.webm)

interactive details
- the title does weird things depending on the scaling

2023-03-24 06:41 UTC, brunobmv commented
![Screen Shot 2023-03-23 at 23 40 43](https://user-images.githubusercontent.com/102827885/227444967-edfe6772-54af-498a-8c0b-a297b53c6d44.jpg)

I fixed everything and attempted to fix the horizontal align.
To me it looked already aligned so i can't really tell the difference.
sorry i have bad eye sight lol

2023-03-24 22:54 UTC, thomaspwang approved these changes
Great work! Looks amazing. Just make sure to name component files capitalized. I made those changes for you this time :)

2023-03-24 23:19 UTC, LeonJia1 approved these changes
looks good but question if you want to make it closer to the figma design by changing to just "Login" and adding the remember me/forgot your pw buttons. I think because we'll have a bear buddies header the "login to bear buddies" might be redundant. its such a minor change though so im just gnna approve

2023-03-24 23:22 UTC, merged