Bb 23 sign up page
plextech-curriculum-sp23/bear-buddies pull request #5
Opened 2023-03-23 00:12 UTC by brunobmv

## Describe your changes:

created signup page. used react forms to get dropdowns. styled the page.

## Proof that your changes work (include screenshots if frontend):
![Screen Shot 2023-03-22 at 16 58 46](https://user-images.githubusercontent.com/102827885/227066404-98667d1c-6e36-4772-85c1-08dfd235365b.jpg)
![Screen Shot 2023-03-22 at 16 58 35](https://user-images.githubusercontent.com/102827885/227066417-5f89d401-5235-4b7c-939e-955319b208d2.jpg)
![Screen Shot 2023-03-22 at 01 24 51 (1)](https://user-images.githubusercontent.com/102827885/227066423-a09a5764-38ab-4757-bcfd-4a38133df74b.jpg)

## Jira Issue ticket number and link:

BB-23 , https://bearbuddies.atlassian.net/browse/BB-23?atlOrigin=eyJpIjoiZDU0NzVkYzQ0MDk5NDliYWE5NWVlNjZkY2Y2MTJlMjEiLCJwIjoiaiJ9 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have DM'd the group chat that I have made a PR and need reviewers.
- [x] I haved moved the Jira issue to "Under Review"
- [x] I have run `npx eslint filename.js` on all JavaScript files I've changed in this PR and fixed all displayed errors

2023-03-23 01:07 UTC, thomaspwang requested changes
Looks great! Almost done, basically. Just like two super small changes.

2023-03-23 01:07 UTC, thomaspwang commented on src/pages/Signup/signup.js
<img width="231" alt="image" src="https://user-images.githubusercontent.com/82493352/227072328-b39b5d26-b169-48c9-ae14-d073973c6ab2.png">

- add slightly more space between the text
- bold the title

reference figma:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/82493352/227072525-a3a4e202-ce0b-46f7-9328-5c1cbd6c293b.png">

2023-03-23 01:07 UTC, thomaspwang commented on src/pages/Signup/signup.js
<img width="119" alt="image" src="https://user-images.githubusercontent.com/82493352/227072499-7915df75-91c1-4e1d-a90c-5c7b8f5efdcd.png">

the dropdown should include a dropdown button

reference figma:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/82493352/227072564-f402b330-d36d-4341-916e-bce8419ec214.png">

2023-03-23 01:07 UTC, thomaspwang commented on src/pages/_app.js
unnecessary changes

do the signup.module.css thing like we discussed

2023-03-23 06:38 UTC, brunobmv commented
![Screen Shot 2023-03-22 at 23 35 07](https://user-images.githubusercontent.com/102827885/227122989-f78cf79d-4485-40f1-9887-ae8767045a7e.jpg)


so i did a bit of syntax gymnastics with the jsx to get the dropdown button.
for some reason, i am not being able to turn the text inside the box grey and make it smaller.
any change i make to it doesn't apply for some reason.
you did not make a comment about this so just wanted to let you know about what i thought about.

2023-03-24 23:00 UTC, thomaspwang requested changes
Amazing! Looks great. Just change one thing about the dropdown logo :)

2023-03-24 23:00 UTC, thomaspwang commented on src/pages/Signup/Signup.js
> +                                <option value="" disabled selected hidden>select gender&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbs
LOL, this is really jank. Instead, add an SVG logo and align it to the right of the input box.

2023-03-24 23:41 UTC, DylanHopkins21 approved these changes
Looks good to me! Made tiny nitpicky change in the CSS and didn't feel the need to make you go change it

2023-03-25 22:28 UTC, thomaspwang approved these changes
Looks good to me!

2023-03-26 03:11 UTC, brunobmv commented
![Screen Shot 2023-03-25 at 20 10 51](https://user-images.githubusercontent.com/102827885/227753145-94845993-96c1-4aa5-8af6-14bdfa7e963c.jpg)

2023-03-26 18:10 UTC, merged