Bb 11 event button component
plextech-curriculum-sp23/bear-buddies pull request #6
Opened 2023-03-23 07:58 UTC by NamitaKhanchu

## Describe your changes:
I created the layout for the created and edit profile buttons with their icons.

## Proof that your changes work (include screenshots and/or for frontend):
<img width="527" alt="Screen Shot 2023-03-23 at 12 43 01 AM" src="https://user-images.githubusercontent.com/72517770/227138412-655c4539-69a0-4768-bf1b-6b7afaaecdda.png">

## Jira Issue ticket number and link:
BB-11
https://bearbuddies.atlassian.net/browse/BB-11

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have DM'd the group chat that I have made a PR and need reviewers.
- [ ] I haved moved the Jira issue to "Under Review"
- [ ] I have run `npx eslint filename.js` on all JavaScript files I've changed in this PR and fixed all displayed errors
- [ ] I have checked the Chrome console in Developer Tools to make sure there are no significant errors

2023-03-23 09:32 UTC, thomaspwang requested changes
great work namita!! just some super small edits that needs to be made :))

2023-03-23 09:32 UTC, thomaspwang commented on src/components/EventButton/EventButton.js
> +import Image from 'next/image';
order imports by library imports first (eg. react, bootstrap, next/image) then local imports

so switch line 5 with line 3

2023-03-23 09:32 UTC, thomaspwang commented on src/components/EventButton/EventButton.module.css
> +
unnecessary empty line

2023-03-23 09:32 UTC, thomaspwang commented on src/components/SearchBar/SearchBar.js
Search Bar changes shouldn't be included in this PR

2023-03-23 09:32 UTC, thomaspwang commented on src/components/SearchBar/SearchBar.module.css
Search Bar changes shouldn't be included in this PR

2023-03-23 09:32 UTC, thomaspwang commented on src/pages/_app.js
i'm pretty sure that line two is not necessary! also, importing bootstrap.min.css here is great, but make sure to remove the import in EventButton.js (since you're importing it again)

2023-03-24 06:21 UTC, DylanHopkins21 requested changes
Hey my only comment on this was about an empty line but I'm not sure really how much it matters! Just made note because Tommy usually points it out

2023-03-24 06:21 UTC, DylanHopkins21 commented on src/components/EventButton/EventButton.js
> +
Unnecessary space at the end of file

2023-03-24 11:16 UTC, thomaspwang approved these changes
Great job! Approved. Make sure in the future to not include files that are not apart of the issue. (AKA your SearchBar code, since this was for the event button)

2023-03-25 03:55 UTC, DylanHopkins21 approved these changes
I changed what I requested, didn't realize I could do that!

2023-03-25 04:04 UTC, merged