Bb 15 search bar component
plextech-curriculum-sp23/bear-buddies pull request #8
Opened 2023-03-26 08:46 UTC by NamitaKhanchu

## Describe your changes:
I completed designing the search bar component

## Proof that your changes work (include screenshots and/or for frontend):
<img width="913" alt="Screen Shot 2023-03-26 at 1 32 33 AM" src="https://user-images.githubusercontent.com/72517770/227765036-0ac4995e-5a95-4338-b02b-3fd9989cbc32.png">

## Jira Issue ticket number and link:
BB-15  
https://bearbuddies.atlassian.net/jira/software/projects/BB/boards/1?selectedIssue=BB-15

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have DM'd the group chat that I have made a PR and need reviewers.
- [ ] I haved moved the Jira issue to "Under Review"
- [ ] I have run `npx eslint filename.js` on all JavaScript files I've changed in this PR and fixed all displayed errors
- [ ] I have checked the Chrome console in Developer Tools to make sure there are no significant errors

2023-03-26 18:18 UTC, thomaspwang requested changes
Looks great! Just one change :))

2023-03-26 18:18 UTC, thomaspwang commented on src/components/SearchBar/SearchBar.js
> +import icon from "./Vector.svg";
there's no ./Vector.svg! if you need the svg, put it in the public folder and import it from there

2023-03-29 20:43 UTC, thomaspwang approved these changes
LGTM (looks good to me)!

2023-03-29 23:34 UTC, brunobmv approved these changes

2023-03-29 23:35 UTC, merged